### PR TITLE
Feature/add initial chart

### PR DESCRIPTION
**Pull request by AnnaPete**
#### What's this PR do?
- Add initial chart information
- Modify existing HTML code
- Add initial chart function (we can make/export more functions as we go on)
#### Where should the reviewer start?
At the beginning, please
#### How should this be manually tested?
n/a
#### Any background context you want to provide?
Charts.js is a complicated thing. You need to `npm install Charts.js` before trying to add any code 
#### What are the relevant tickets?
n/a
#### Screenshots (if appropriate)
No, I'm too tired for pictures
#### Questions:
Only about Chart.js

### CODE REVIEW

**Comment by AnnaPete** [comment]
**UPDATE:  `npm install chart.js`

**Review by cieragrace — APPROVED** [review]
Good work getting the widget to show on the page. Now we just need to link our data

**Review by crgweller — COMMENTED** [review]
Good work!

**Review by keenans1 — APPROVED** [review]
nice work!

**Pull request merged**
