### PR TITLE
Feature/refactor css

### PR DESCRIPTION
**Pull request by AnnaPete**
#### What's this PR do?
- Refactor CSS
- Add HTML containers for styling
- Modify query selectors

#### Where should the reviewer start?
at the css file

#### How should this be manually tested?
page load

#### Any background context you want to provide?
no. let us be done!

#### What are the relevant tickets?
n/a

#### Screenshots (if appropriate)
never

#### Questions:
none

### CODE REVIEW

**Review by cieragrace — APPROVED** [review]
Just need a few tweeks

**Comment by crgweller** [comment]
Nice work!

**Review by keenans1 — APPROVED** [review]
looks good

**Review by crgweller — COMMENTED** [review]
Almost done!

**Pull request merged**
